# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

#    app.open_weather:
#        class: AppBundle\Providers\OpenWeatherProvider
#        arguments: ['%owm_apikey%']
#    app.apixu_weather:
#        class: AppBundle\Providers\ApixuWeatherProvider
#        arguments: ['%apixu_apikey%']
#    app.delegating_weather:
#        class: AppBundle\Providers\DelegatingWeatherProvider
#        arguments:
#            - '@app.open_weather'
#            - '@app.apixu_weather'
#    app.cached_weather:
#        class: AppBundle\Providers\CachedWeatherProvider
#        arguments:
#            - '%lifetime%'
#            - '@app.open_weather'